<a href="https://colab.research.google.com/github/sukhyun1017/NLP-study/blob/main/3_NLP_RNN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10))) #hidden_units = 3
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_5 (SimpleRNN)    (8, 3)                    42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, input_length=2, input_dim=10)) #input_length = timesteps
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_8 (SimpleRNN)    (None, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, batch_size=8, input_length=2, input_dim=10, return_sequences=True))
model.summary()
# outputshape = ( batch_size,timesteps,output_dim)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_4 (SimpleRNN)    (8, 2, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [10]:
import numpy as np

timesteps = 10 #자연어 처리에서 보통 문장의 길이
input_dim = 4 #단어벡터의 차원
hidden_units = 8 #메모리셀의 용량

# 입력에 해당되는 2D 텐서
inputs = np.random.random((timesteps, input_dim))

# 초기 은닉 상태는 0(벡터)로 초기화
hidden_state_t = np.zeros((hidden_units,)) 

print('초기 은닉 상태 :',hidden_state_t)
print('inputs :',inputs)

초기 은닉 상태 : [0. 0. 0. 0. 0. 0. 0. 0.]
inputs : [[0.83663188 0.83145777 0.88115284 0.12150876]
 [0.14897721 0.87045544 0.95159454 0.3688673 ]
 [0.93813139 0.36090896 0.63045033 0.38560026]
 [0.5993228  0.1725741  0.65722088 0.46796156]
 [0.73867572 0.63841294 0.85572888 0.55388341]
 [0.62595175 0.62118901 0.8042909  0.06638747]
 [0.08156678 0.58944173 0.87679046 0.886089  ]
 [0.71403292 0.15854616 0.13629849 0.5856943 ]
 [0.04950884 0.94045878 0.47510347 0.96356519]
 [0.4226777  0.46859876 0.27647719 0.43930824]]


In [11]:
Wx = np.random.random((hidden_units, input_dim))  # (8, 4)크기의 2D 텐서 생성. 입력에 대한 가중치.
Wh = np.random.random((hidden_units, hidden_units)) # (8, 8)크기의 2D 텐서 생성. 은닉 상태에 대한 가중치.
b = np.random.random((hidden_units,)) # (8,)크기의 1D 텐서 생성. 이 값은 편향(bias).

print('가중치 Wx의 크기(shape) :',np.shape(Wx))
print('가중치 Wh의 크기(shape) :',np.shape(Wh))
print('편향의 크기(shape) :',np.shape(b))

가중치 Wx의 크기(shape) : (8, 4)
가중치 Wh의 크기(shape) : (8, 8)
편향의 크기(shape) : (8,)


In [14]:
total_hidden_states = []

# 각 시점 별 입력값.
for input_t in inputs:

  # Wx * Xt + Wh * Ht-1 + b(bias)
  output_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh,hidden_state_t) + b)

  # 각 시점 t별 메모리 셀의 출력의 크기는 (timestep t, output_dim)
  # 각 시점의 은닉 상태의 값을 계속해서 누적
  total_hidden_states.append(list(output_t))
  hidden_state_t = output_t

# 출력 시 값을 깔끔하게 해주는 용도.
total_hidden_states = np.stack(total_hidden_states, axis = 0) 

# (timesteps, output_dim)
print('모든 시점의 은닉 상태 :')
print(total_hidden_states)

모든 시점의 은닉 상태 :
[[0.99995732 0.99972106 0.99971868 0.99998729 0.99997155 0.99997491
  0.99999924 0.99996054]
 [0.99996084 0.99949792 0.99971999 0.99998241 0.99994715 0.99998359
  0.99999853 0.99994347]
 [0.99991811 0.99955407 0.9996866  0.9999861  0.99997038 0.99995486
  0.99999831 0.99996837]
 [0.99988324 0.99912231 0.99964422 0.99998212 0.99995005 0.99994675
  0.99999634 0.99995815]
 [0.99996969 0.99975042 0.9998228  0.99998909 0.99997841 0.99998366
  0.99999919 0.99997926]
 [0.99991159 0.99937709 0.99957161 0.99998205 0.9999474  0.9999552
  0.99999808 0.9999329 ]
 [0.99997056 0.99953934 0.99982959 0.9999851  0.99996207 0.99998876
  0.9999983  0.99997365]
 [0.99975471 0.99892828 0.99931558 0.99997518 0.99994524 0.99989589
  0.99999403 0.99993496]
 [0.99996582 0.99962645 0.99971619 0.99998045 0.9999621  0.99998795
  0.99999845 0.99995614]
 [0.99980926 0.99890408 0.99925023 0.99997161 0.99992638 0.99992527
  0.99999486 0.99989885]]


In [ ]:
'''
#parameter 갯수
vocab_size = 5000
embedding_dim = 100
hidden_size = 128

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_size))
model.add(Dense(1, activation='sigmoid'))
model.summary() 

Embedding = 5,000(input) * 100(embedding) = 500,000
Wx = 100(embedding) * 128(hidden) = 12,800
Wh = 128 * 128 = 16,384
bias(hidden)  = 128
Wy = 128
bias(output) = 1
'''

SimpleRNN

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [3]:
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [4]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X)
print(train_X.shape)

(1, 4, 5)


In [5]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True) #return_state 마지막 은닉상태
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[ 0.13559909 -0.8650628   0.65824383]
  [-0.97348595 -0.44317752  0.9612919 ]
  [ 0.43485233 -0.35006428  0.98906565]
  [-0.80014014 -0.84139955  0.55385596]]], shape: (1, 4, 3)
last hidden state : [[-0.80014014 -0.84139955  0.55385596]], shape: (1, 3)


LSTM

In [7]:
lstm = LSTM(3, return_sequences=True, return_state=True) #return_sequences=Treu 전체 은닉상태를 보여줌
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[[ 0.00570436  0.09656944  0.32211107]
  [ 0.01124066  0.02518772  0.27048156]
  [-0.1566962  -0.00289081  0.25255582]
  [ 0.10423258 -0.11369191  0.19070013]]], shape: (1, 4, 3)
last hidden state : [[ 0.10423258 -0.11369191  0.19070013]], shape: (1, 3)
last cell state : [[ 0.18365766 -0.19299483  0.29259893]], shape: (1, 3)


Bidirectional LSTM

In [8]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [11]:
#return_sequences=False 면 정방향 마지막 히든상태와 역방향 첫 히든상태가 합쳐짐
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape: (1, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [12]:
#return_sequences=True 면 정방향 마지막 히든상태와 역방향 마지막 히든상태가 합쳐짐
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)
